name: Amzn CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
          
      - name: Установка пакетов
        run: yarn install
  
      - name: Создание переменных окружения
        run: echo "${{ secrets.ENV_FILE }};" > .env
      
      - name: Сборка приложения
        run: yarn build

