export enum ENV {
  DATABASE_URL = 'DATABASE_URL',
  APP_PORT = 'APP_PORT',
  APP_NAME = 'APP_NAME',
  APP_HOST = 'APP_HOST',
  APP_PREFIX = 'APP_PREFIX',
  JWT_SECRET = 'JWT_SECRET',
  COOKIE_SECRET = 'COOKIE_SECRET',
  SENTRY_DSN = 'SENTRY_DSN',
  ENVIRONMENT = 'ENVIRONMENT',
  PHONE_NUMBER_FORMAT = '+375 (##) ### ## ##',
}

export enum ENVIRONMENT {
  DEVELOPMENT = 'development',
  STAGING = 'staging',
  PRODUCTION = 'production',
}
